/*
 * Copyright (C) 2009-2011 RtcNbClient Team (http://rtcnbclient.wmi.amu.edu.pl/)
 *
 * This file is part of RtcNbClient.
 *
 * RtcNbClient is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * RtcNbClient is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RtcNbClient. If not, see <http://www.gnu.org/licenses/>.
 */
package pl.edu.amu.wmi.kino.rtc.client.workitems.panels;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author michu
 */
public class RtcRoundedSectionPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = -2661776021945120743L;
	private String labelText = "";

    /** Creates new form RtcRoundedSectionPanel */
    public RtcRoundedSectionPanel() {
        initComponents();
        setVisible(true);
    }

    public void setLabelText(String s) {
        labelText = s;
    }

    @Override
    protected void paintBorder(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;

        Shape round = new RoundRectangle2D.Float(0, 0, getWidth() - 1, getHeight(), 6, 6);
        g2d.setStroke(new BasicStroke(1));

        GradientPaint gradient = new GradientPaint(0, 0, Color.decode("#B7CADE"), 0, 30, Color.WHITE);
        g2d.setPaint(gradient);

        g2d.draw(round);
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
    }

    @Override
    public void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;

        GradientPaint gradient = new GradientPaint(0, 0, Color.decode("#E0E8F1"), 0, 30, Color.WHITE);
        g2d.setPaint(gradient);

        Shape round = new RoundRectangle2D.Float(2, 2, getWidth() - 4, getHeight(), 3, 3);
        g2d.fill(round);

        Polygon p = new Polygon(new int[]{7, 15, 11}, new int[]{13, 13, 17}, 3);
        g2d.setColor(Color.decode("#194C7F"));
        g2d.fill(p);
        g2d.draw(p);

        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
        
        if(!labelText.equals("")) {

            Font font = new Font("Tahoma", Font.BOLD, 11);
            g2d.setFont(font);

            g2d.drawString(labelText, 20, 20);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
