/*
 * Copyright (C) 2009-2011 RtcNbClient Team (http://rtcnbclient.wmi.amu.edu.pl/)
 *
 * This file is part of RtcNbClient.
 *
 * RtcNbClient is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * RtcNbClient is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RtcNbClient. If not, see <http://www.gnu.org/licenses/>.
 */
package pl.edu.amu.wmi.kino.rtc.client.workitems.panels;

import javax.swing.JPanel;
import org.openide.util.HelpCtx;
import org.openide.util.Lookup;
import pl.edu.amu.wmi.kino.rtc.client.workitems.WorkItemPanelGenerator;
import pl.edu.amu.wmi.kino.rtc.client.workitems.attributes.RtcWorkItemAttributeSet;

/**
 *
 * @author michu
 */
public class RtcWorkItemOverviewLayout extends javax.swing.JPanel implements HelpCtx.Provider {

	private static final long serialVersionUID = 1173531234565122913L;

	/** Creates new form RtcWorkItemOverviewPanel */
    public RtcWorkItemOverviewLayout(RtcWorkItemAttributeSet.RtcWorkItemAttributeCategory cat) {
        initComponents();
        
        for (RtcWorkItemAttributeSet.RtcWorkItemAttributeSection sec : cat) {

            JPanel sectionPanel;
            JPanel sectionHeader;
            
            if (sec.getSlot().equals(RtcWorkItemAttributeSet.SectionSlot.DETAILS)) {
                sectionPanel = jDetailsPanel;
                sectionHeader = jDetailsSectionLabel;
            } else if (sec.getSlot().equals(RtcWorkItemAttributeSet.SectionSlot.QUICKINFO)) {
                sectionPanel = jQuickInfoPanel;
                sectionHeader = jQuickInfoSectionLabel;
            } else if (sec.getSlot().equals(RtcWorkItemAttributeSet.SectionSlot.DESCRIPTION)) {
                sectionPanel = jDescriptionPanel;
                sectionHeader = jDescriptionSectionLabel;
            } else if (sec.getSlot().equals(RtcWorkItemAttributeSet.SectionSlot.DISCUSSION)) {
                sectionPanel = jDiscussionPanel;
                sectionHeader = jDiscussionSectionLabel;
            } else {
                continue;
            }

            Lookup.getDefault().lookup(WorkItemPanelGenerator.class).fillProperies(sec, sectionPanel, (RtcRoundedSectionPanel) sectionHeader);
        }

        setFocusable(true);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jSplitPaneMain = new javax.swing.JSplitPane();
        jRightPanel = new javax.swing.JSplitPane();
        jTopPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jDescriptionSectionLabel = new RtcRoundedSectionPanel();
        jDescriptionPanel = new javax.swing.JPanel();
        jBottomPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jDiscussionSectionLabel = new RtcRoundedSectionPanel();
        jDiscussionPanel = new javax.swing.JPanel();
        jLeftPanel = new javax.swing.JPanel();
        jDetailsPanel = new javax.swing.JPanel();
        jQuickInfoPanel = new javax.swing.JPanel();
        jDetailsSectionLabel = new RtcRoundedSectionPanel();
        jQuickInfoSectionLabel = new RtcRoundedSectionPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane.setBorder(null);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jSplitPaneMain.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPaneMain.setBorder(null);
        jSplitPaneMain.setDividerLocation(450);
        jSplitPaneMain.setDividerSize(15);
        jSplitPaneMain.setResizeWeight(0.5);
        jSplitPaneMain.setContinuousLayout(true);
        jSplitPaneMain.setDoubleBuffered(true);
        jSplitPaneMain.setMinimumSize(new java.awt.Dimension(1, 1));
        jSplitPaneMain.setOneTouchExpandable(true);
        jSplitPaneMain.setOpaque(false);
        jSplitPaneMain.setPreferredSize(new java.awt.Dimension(557, 600));

        jRightPanel.setBorder(null);
        jRightPanel.setDividerLocation(250);
        jRightPanel.setDividerSize(15);
        jRightPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jRightPanel.setResizeWeight(0.5);
        jRightPanel.setContinuousLayout(true);
        jRightPanel.setDoubleBuffered(true);
        jRightPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        jRightPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        jRightPanel.setOneTouchExpandable(true);
        jRightPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        jTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        jTopPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jTopPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        jTopPanel.setMinimumSize(new java.awt.Dimension(0, 1));
        jTopPanel.setLayout(new javax.swing.BoxLayout(jTopPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jDescriptionSectionLabel.setMinimumSize(new java.awt.Dimension(0, 0));
        jDescriptionSectionLabel.setPreferredSize(new java.awt.Dimension(157, 36));

        javax.swing.GroupLayout jDescriptionSectionLabelLayout = new javax.swing.GroupLayout(jDescriptionSectionLabel);
        jDescriptionSectionLabel.setLayout(jDescriptionSectionLabelLayout);
        jDescriptionSectionLabelLayout.setHorizontalGroup(
            jDescriptionSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jDescriptionSectionLabelLayout.setVerticalGroup(
            jDescriptionSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jDescriptionPanel.setBackground(new java.awt.Color(255, 255, 255));
        jDescriptionPanel.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jDescriptionPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        jDescriptionPanel.setLayout(new javax.swing.BoxLayout(jDescriptionPanel, javax.swing.BoxLayout.PAGE_AXIS));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDescriptionSectionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(jDescriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jDescriptionSectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDescriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
        );

        jTopPanel.add(jPanel4);

        jRightPanel.setLeftComponent(jTopPanel);

        jBottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        jBottomPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jBottomPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        jBottomPanel.setMinimumSize(new java.awt.Dimension(0, 1));
        jBottomPanel.setPreferredSize(new java.awt.Dimension(206, 300));
        jBottomPanel.setLayout(new javax.swing.BoxLayout(jBottomPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(196, 300));

        javax.swing.GroupLayout jDiscussionSectionLabelLayout = new javax.swing.GroupLayout(jDiscussionSectionLabel);
        jDiscussionSectionLabel.setLayout(jDiscussionSectionLabelLayout);
        jDiscussionSectionLabelLayout.setHorizontalGroup(
            jDiscussionSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jDiscussionSectionLabelLayout.setVerticalGroup(
            jDiscussionSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jDiscussionPanel.setBackground(new java.awt.Color(255, 255, 255));
        jDiscussionPanel.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jDiscussionPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        jDiscussionPanel.setLayout(new javax.swing.BoxLayout(jDiscussionPanel, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDiscussionSectionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDiscussionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jDiscussionSectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDiscussionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
        );

        jBottomPanel.add(jPanel6);

        jRightPanel.setRightComponent(jBottomPanel);

        jSplitPaneMain.setRightComponent(jRightPanel);

        jLeftPanel.setBackground(new java.awt.Color(255, 255, 255));
        jLeftPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jLeftPanel.setMinimumSize(new java.awt.Dimension(1, 0));

        jDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));
        jDetailsPanel.setPreferredSize(new java.awt.Dimension(0, 300));
        jDetailsPanel.setLayout(new javax.swing.BoxLayout(jDetailsPanel, javax.swing.BoxLayout.PAGE_AXIS));

        jQuickInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        jQuickInfoPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        jQuickInfoPanel.setLayout(new javax.swing.BoxLayout(jQuickInfoPanel, javax.swing.BoxLayout.PAGE_AXIS));

        javax.swing.GroupLayout jDetailsSectionLabelLayout = new javax.swing.GroupLayout(jDetailsSectionLabel);
        jDetailsSectionLabel.setLayout(jDetailsSectionLabelLayout);
        jDetailsSectionLabelLayout.setHorizontalGroup(
            jDetailsSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jDetailsSectionLabelLayout.setVerticalGroup(
            jDetailsSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jQuickInfoSectionLabelLayout = new javax.swing.GroupLayout(jQuickInfoSectionLabel);
        jQuickInfoSectionLabel.setLayout(jQuickInfoSectionLabelLayout);
        jQuickInfoSectionLabelLayout.setHorizontalGroup(
            jQuickInfoSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jQuickInfoSectionLabelLayout.setVerticalGroup(
            jQuickInfoSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLeftPanelLayout = new javax.swing.GroupLayout(jLeftPanel);
        jLeftPanel.setLayout(jLeftPanelLayout);
        jLeftPanelLayout.setHorizontalGroup(
            jLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
            .addComponent(jQuickInfoSectionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jQuickInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
            .addComponent(jDetailsSectionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLeftPanelLayout.setVerticalGroup(
            jLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLeftPanelLayout.createSequentialGroup()
                .addComponent(jDetailsSectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jQuickInfoSectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jQuickInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
        );

        jSplitPaneMain.setLeftComponent(jLeftPanel);

        jScrollPane.setViewportView(jSplitPaneMain);

        add(jScrollPane);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBottomPanel;
    private javax.swing.JPanel jDescriptionPanel;
    private javax.swing.JPanel jDescriptionSectionLabel;
    private javax.swing.JPanel jDetailsPanel;
    private javax.swing.JPanel jDetailsSectionLabel;
    private javax.swing.JPanel jDiscussionPanel;
    private javax.swing.JPanel jDiscussionSectionLabel;
    private javax.swing.JPanel jLeftPanel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jQuickInfoPanel;
    private javax.swing.JPanel jQuickInfoSectionLabel;
    private javax.swing.JSplitPane jRightPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSplitPane jSplitPaneMain;
    private javax.swing.JPanel jTopPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public HelpCtx getHelpCtx() {
         return new HelpCtx(RtcWorkItemOverviewLayout.class);
    }
}
