/*
 * Copyright (C) 2009-2011 RtcNbClient Team (http://rtcnbclient.wmi.amu.edu.pl/)
 *
 * This file is part of RtcNbClient.
 *
 * RtcNbClient is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * RtcNbClient is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RtcNbClient. If not, see <http://www.gnu.org/licenses/>.
 */
package pl.edu.amu.wmi.kino.rtc.client.workitems.panels;

import org.openide.util.HelpCtx;
import org.openide.util.Lookup;
import pl.edu.amu.wmi.kino.rtc.client.workitems.WorkItemPanelGenerator;
import pl.edu.amu.wmi.kino.rtc.client.workitems.attributes.RtcWorkItemAttributeSet.RtcWorkItemAttributeSection;

/**
 *
 * @author michu
 */
public class RtcWorkItemApprovalsLayout extends javax.swing.JPanel implements HelpCtx.Provider  {

	private static final long serialVersionUID = 1949851020273294756L;

	/** Creates new form RtcWorkItemApprovalsCategory */
    public RtcWorkItemApprovalsLayout(RtcWorkItemAttributeSection sec) {
        initComponents();
        setFocusable(true);

        Lookup.getDefault().lookup(WorkItemPanelGenerator.class).fillProperies(sec, jApprovalsPanel, (RtcRoundedSectionPanel) jApprovalsSectionHeader);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTopPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jApprovalsSectionHeader = new RtcRoundedSectionPanel();
        jApprovalsPanel = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setBorder(null);

        jTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        jTopPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jTopPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        jTopPanel.setMinimumSize(new java.awt.Dimension(0, 200));
        jTopPanel.setLayout(new javax.swing.BoxLayout(jTopPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jApprovalsSectionHeader.setPreferredSize(new java.awt.Dimension(157, 15));

        javax.swing.GroupLayout jApprovalsSectionHeaderLayout = new javax.swing.GroupLayout(jApprovalsSectionHeader);
        jApprovalsSectionHeader.setLayout(jApprovalsSectionHeaderLayout);
        jApprovalsSectionHeaderLayout.setHorizontalGroup(
            jApprovalsSectionHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        jApprovalsSectionHeaderLayout.setVerticalGroup(
            jApprovalsSectionHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jApprovalsPanel.setBackground(new java.awt.Color(255, 255, 255));
        jApprovalsPanel.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jApprovalsPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        jApprovalsPanel.setLayout(new javax.swing.BoxLayout(jApprovalsPanel, javax.swing.BoxLayout.PAGE_AXIS));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jApprovalsSectionHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addComponent(jApprovalsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jApprovalsSectionHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jApprovalsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
        );

        jTopPanel.add(jPanel4);

        jScrollPane1.setViewportView(jTopPanel);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jApprovalsPanel;
    private javax.swing.JPanel jApprovalsSectionHeader;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jTopPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public HelpCtx getHelpCtx() {
        return new HelpCtx(RtcWorkItemApprovalsLayout.class);
    }

}
