/*
 * Copyright (C) 2009-2011 RtcNbClient Team (http://rtcnbclient.wmi.amu.edu.pl/)
 *
 * This file is part of RtcNbClient.
 *
 * RtcNbClient is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * RtcNbClient is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RtcNbClient. If not, see <http://www.gnu.org/licenses/>.
 */
package pl.edu.amu.wmi.kino.rtc.client.workitems.panels;

import javax.swing.JPanel;
import org.openide.util.HelpCtx;
import org.openide.util.Lookup;
import pl.edu.amu.wmi.kino.rtc.client.workitems.WorkItemPanelGenerator;
import pl.edu.amu.wmi.kino.rtc.client.workitems.attributes.RtcWorkItemAttributeSet;

/**
 *
 * @author michu
 */
public class RtcWorkItemLinksLayout extends javax.swing.JPanel implements HelpCtx.Provider {

	private static final long serialVersionUID = -450321398984554524L;
	/** Creates new form RtcWorkItemLinksPanel */
    public RtcWorkItemLinksLayout(RtcWorkItemAttributeSet.RtcWorkItemAttributeCategory cat) {
        initComponents();
        setFocusable(true);

        for (RtcWorkItemAttributeSet.RtcWorkItemAttributeSection sec : cat) {

            JPanel sectionPanel;
            JPanel sectionHeader;

            if (sec.getSlot().equals(RtcWorkItemAttributeSet.SectionSlot.ATTACHMENTS)) {
                sectionPanel = jAttachmentsPanel;
                sectionHeader = jAttachmentsSectionLabel;
            } else if (sec.getSlot().equals(RtcWorkItemAttributeSet.SectionSlot.LINKS)) {
                sectionPanel = jLinksPanel;
                sectionHeader = jLinksSectionLabel;
            } else if (sec.getSlot().equals(RtcWorkItemAttributeSet.SectionSlot.SUBSCRIBERS)) {
                sectionPanel = jSubscribersPanel;
                sectionHeader = jSubscribersSectionLabel;
            } else {
                continue;
            }

            Lookup.getDefault().lookup(WorkItemPanelGenerator.class).fillProperies(sec, sectionPanel, (RtcRoundedSectionPanel) sectionHeader);
        }
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jSplitPaneMain = new javax.swing.JSplitPane();
        jRightPanel = new javax.swing.JSplitPane();
        jTopPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jAttachmentsSectionLabel = new RtcRoundedSectionPanel();
        jAttachmentsPanel = new javax.swing.JPanel();
        jBottomPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jSubscribersSectionLabel = new RtcRoundedSectionPanel();
        jSubscribersPanel = new javax.swing.JPanel();
        jLeftPanel = new javax.swing.JPanel();
        jLinksPanel = new javax.swing.JPanel();
        jLinksSectionLabel = new RtcRoundedSectionPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane.setBorder(null);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jSplitPaneMain.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPaneMain.setBorder(null);
        jSplitPaneMain.setDividerSize(15);
        jSplitPaneMain.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPaneMain.setResizeWeight(0.5);
        jSplitPaneMain.setContinuousLayout(true);
        jSplitPaneMain.setDoubleBuffered(true);
        jSplitPaneMain.setOneTouchExpandable(true);
        jSplitPaneMain.setOpaque(false);
        jSplitPaneMain.setPreferredSize(new java.awt.Dimension(557, 600));

        jRightPanel.setBorder(null);
        jRightPanel.setDividerLocation(400);
        jRightPanel.setDividerSize(15);
        jRightPanel.setResizeWeight(0.5);
        jRightPanel.setContinuousLayout(true);
        jRightPanel.setDoubleBuffered(true);
        jRightPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        jRightPanel.setMinimumSize(new java.awt.Dimension(0, 250));
        jRightPanel.setOneTouchExpandable(true);
        jRightPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        jTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        jTopPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jTopPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        jTopPanel.setMinimumSize(new java.awt.Dimension(200, 0));
        jTopPanel.setPreferredSize(new java.awt.Dimension(500, 250));
        jTopPanel.setLayout(new javax.swing.BoxLayout(jTopPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jAttachmentsSectionLabel.setPreferredSize(new java.awt.Dimension(157, 36));

        javax.swing.GroupLayout jAttachmentsSectionLabelLayout = new javax.swing.GroupLayout(jAttachmentsSectionLabel);
        jAttachmentsSectionLabel.setLayout(jAttachmentsSectionLabelLayout);
        jAttachmentsSectionLabelLayout.setHorizontalGroup(
            jAttachmentsSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jAttachmentsSectionLabelLayout.setVerticalGroup(
            jAttachmentsSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jAttachmentsPanel.setBackground(new java.awt.Color(255, 255, 255));
        jAttachmentsPanel.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jAttachmentsPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        jAttachmentsPanel.setLayout(new javax.swing.BoxLayout(jAttachmentsPanel, javax.swing.BoxLayout.PAGE_AXIS));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAttachmentsSectionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
            .addComponent(jAttachmentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jAttachmentsSectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAttachmentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
        );

        jTopPanel.add(jPanel4);

        jRightPanel.setLeftComponent(jTopPanel);

        jBottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        jBottomPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jBottomPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        jBottomPanel.setMinimumSize(new java.awt.Dimension(200, 0));
        jBottomPanel.setPreferredSize(new java.awt.Dimension(206, 300));
        jBottomPanel.setLayout(new javax.swing.BoxLayout(jBottomPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(196, 300));

        javax.swing.GroupLayout jSubscribersSectionLabelLayout = new javax.swing.GroupLayout(jSubscribersSectionLabel);
        jSubscribersSectionLabel.setLayout(jSubscribersSectionLabelLayout);
        jSubscribersSectionLabelLayout.setHorizontalGroup(
            jSubscribersSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        jSubscribersSectionLabelLayout.setVerticalGroup(
            jSubscribersSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jSubscribersPanel.setBackground(new java.awt.Color(255, 255, 255));
        jSubscribersPanel.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jSubscribersPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        jSubscribersPanel.setLayout(new javax.swing.BoxLayout(jSubscribersPanel, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSubscribersSectionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSubscribersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jSubscribersSectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSubscribersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
        );

        jBottomPanel.add(jPanel6);

        jRightPanel.setRightComponent(jBottomPanel);

        jSplitPaneMain.setLeftComponent(jRightPanel);

        jLeftPanel.setBackground(new java.awt.Color(255, 255, 255));
        jLeftPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jLeftPanel.setMinimumSize(new java.awt.Dimension(0, 300));

        jLinksPanel.setBackground(new java.awt.Color(255, 255, 255));
        jLinksPanel.setPreferredSize(new java.awt.Dimension(0, 300));
        jLinksPanel.setLayout(new javax.swing.BoxLayout(jLinksPanel, javax.swing.BoxLayout.PAGE_AXIS));

        javax.swing.GroupLayout jLinksSectionLabelLayout = new javax.swing.GroupLayout(jLinksSectionLabel);
        jLinksSectionLabel.setLayout(jLinksSectionLabelLayout);
        jLinksSectionLabelLayout.setHorizontalGroup(
            jLinksSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        jLinksSectionLabelLayout.setVerticalGroup(
            jLinksSectionLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLeftPanelLayout = new javax.swing.GroupLayout(jLeftPanel);
        jLeftPanel.setLayout(jLeftPanelLayout);
        jLeftPanelLayout.setHorizontalGroup(
            jLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLinksSectionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLinksPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        jLeftPanelLayout.setVerticalGroup(
            jLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLeftPanelLayout.createSequentialGroup()
                .addComponent(jLinksSectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLinksPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
        );

        jSplitPaneMain.setRightComponent(jLeftPanel);

        jScrollPane.setViewportView(jSplitPaneMain);

        add(jScrollPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jAttachmentsPanel;
    private javax.swing.JPanel jAttachmentsSectionLabel;
    private javax.swing.JPanel jBottomPanel;
    private javax.swing.JPanel jLeftPanel;
    private javax.swing.JPanel jLinksPanel;
    private javax.swing.JPanel jLinksSectionLabel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSplitPane jRightPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSplitPane jSplitPaneMain;
    private javax.swing.JPanel jSubscribersPanel;
    private javax.swing.JPanel jSubscribersSectionLabel;
    private javax.swing.JPanel jTopPanel;
    // End of variables declaration//GEN-END:variables
    @Override
    public HelpCtx getHelpCtx() {
        return new HelpCtx(RtcWorkItemLinksLayout.class);
    }
}
